// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5NFAxP-t8Rhoj1UPsk0prQkLbiJKj9fw',
    appId: '1:806710041554:web:your-web-app-id',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    authDomain: 'joybank-9636f.firebaseapp.com',
    storageBucket: 'joybank-9636f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NFAxP-t8Rhoj1UPsk0prQkLbiJKj9fw',
    appId: '1:806710041554:android:9ca8815db61842bb79060b',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5NFAxP-t8Rhoj1UPsk0prQkLbiJKj9fw',
    appId: '1:806710041554:ios:your-ios-app-id',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
    iosBundleId: 'com.sedev.joybank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5NFAxP-t8Rhoj1UPsk0prQkLbiJKj9fw',
    appId: '1:806710041554:macos:your-macos-app-id',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
    iosBundleId: 'com.sedev.joybank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5NFAxP-t8Rhoj1UPsk0prQkLbiJKj9fw',
    appId: '1:806710041554:windows:your-windows-app-id',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
  );
}
